services:
  postgres:
    image: postgres:16-alpine
    container_name: camagru-postgres
    restart: always
    env_file: .env
    ports:
        - '5432:5432'
    networks:
      - camagru
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-vol:/var/lib/postgresql/data

  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: camagru-api
    networks:
      - camagru
    restart: always

  web:
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: camagru-web
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: always
    networks:
      - camagru

networks:
  camagru:
    driver: bridge
    name: camagru

volumes:
    postgres-vol:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '~/camagru-postgres-data'