CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    token VARCHAR(255),
    is_active BOOLEAN DEFAULT FALSE,
    receive_email BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS images (
    id SERIAL PRIMARY KEY,
    image_id VARCHAR(255) NOT NULL UNIQUE,
    likes INT DEFAULT 0,
    username VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    id SERIAL PRIMARY KEY,
    image_id VARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL,
    comment TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
    id SERIAL PRIMARY KEY,
    image_id VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL
)